name: Release Build

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            repository/main/installation.sh
            repository/main/dcmsg
